// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tilskuddsapp.Data;

#nullable disable

namespace Tilskuddsapp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260830164948_FixSupervisorGrantCasesRelation")]
    partial class FixSupervisorGrantCasesRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Tilskuddsapp.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DoctorType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DoctorId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("Tilskuddsapp.Models.Expense", b =>
                {
                    b.Property<int>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpenseType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GrantCaseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExpenseId");

                    b.HasIndex("GrantCaseId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Tilskuddsapp.Models.GrantCase", b =>
                {
                    b.Property<int>("GrantCaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ApprovedGrant")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("DoctorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GrantCaseStatus")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MaximumGrant")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SupervisionHours")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SupervisorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("GrantCaseId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("GrantCases");
                });

            modelBuilder.Entity("Tilskuddsapp.Models.Supervisor", b =>
                {
                    b.Property<int>("SupervisorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SupervisorType")
                        .HasColumnType("INTEGER");

                    b.HasKey("SupervisorId");

                    b.ToTable("Supervisors");
                });

            modelBuilder.Entity("Tilskuddsapp.Models.Expense", b =>
                {
                    b.HasOne("Tilskuddsapp.Models.GrantCase", "GrantCase")
                        .WithMany("Expenses")
                        .HasForeignKey("GrantCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrantCase");
                });

            modelBuilder.Entity("Tilskuddsapp.Models.GrantCase", b =>
                {
                    b.HasOne("Tilskuddsapp.Models.Doctor", "Doctor")
                        .WithMany("GrantCases")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tilskuddsapp.Models.Supervisor", "Supervisor")
                        .WithMany("GrantCases")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Doctor");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("Tilskuddsapp.Models.Doctor", b =>
                {
                    b.Navigation("GrantCases");
                });

            modelBuilder.Entity("Tilskuddsapp.Models.GrantCase", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("Tilskuddsapp.Models.Supervisor", b =>
                {
                    b.Navigation("GrantCases");
                });
#pragma warning restore 612, 618
        }
    }
}
